[package]
name = "flax"
version = "0.1.0"
edition = "2021"
authors = ["Tei Leelo Roberts <ten3roberts@gmail.com>"]
description = "An archetypical ECS"
documentation = "https://docs.rs/flax"
repository = "https://github.com/ten3roberts/flax"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_refcell = "0.1.8"
bitflags = "1.3.2"
eyre = "0.6.8"
itertools = "0.10.3"
paste = "1.0.7"
rayon = { version = "1.5.3", optional = true }
smallvec = "1.8.0"
thiserror = "1.0.31"
tracing = "0.1.35"

[dev-dependencies]
itertools = "0.10.3"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
test-log = { version = "0.2.11", default_features = false, features = [
    "trace",
] }

[features]
default = ["parallel"]
parallel = ["rayon"]
