codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 60%
    patch:
      status:
        patch: false
      default:
        target: 60%  # new contributions should have a coverage at least equal to target
