[package]
name = "asteroids"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flax = { path = "../", default-features = false, features = [
    "flume",
    "derive",
] }
macroquad = "0.3.8"
# sapp-wasm = "=0.1.26"

flume = { version = "0.10.14", default_features = false }
rand = { version = "0.8.5", default_features = false, features = ["std_rng"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
tracing-tree = "0.2.1"
itertools = "0.10"
anyhow = "1.0.70"
