name: Asteroids

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  asteroids:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
      - run: cargo build --release --package asteroids --target wasm32-unknown-unknown --manifest-path=asteroids/Cargo.toml
      - run: mv ./target/wasm32-unknown-unknown/release/asteroids.wasm ./asteroids/public
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: asteroids
          path: asteroids/public
