name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: taiki-e/install-action@nextest
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --all-features

  test_miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: miri

      - uses: taiki-e/install-action@nextest

      - name: Run cargo miri
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: nextest run --no-default-features --features std,serde,flume,derive

  test_nostd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: taiki-e/install-action@nextest

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --no-default-features

  lint_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features

  test_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Run cargo test (doc)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --all-features

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: miri

      - uses: taiki-e/install-action@cargo-tarpaulin

      - name: Run cargo tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --features std,flume,serde --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
